pipeline:
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags:
    ngPipelines: ""
    pipelineservice: ""
  stages:
    - stage:
        name: cs
        identifier: cs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - parallel:
                  - step:
                      type: ShellScript
                      name: ShellScript_1
                      identifier: ShellScript_1
                      timeout: 10m
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: |-
                              sleep 20
                              echo "ok"
                        environmentVariables: []
                        outputVariables: []
                  - stepGroup:
                      name: sg
                      identifier: sg
                      steps:
                        - step:
                            type: HarnessApproval
                            name: HarnessApproval_1
                            identifier: HarnessApproval_1
                            timeout: 1d
                            spec:
                              approvalMessage: Please review the following information and approve the pipeline progression
                              includePipelineExecutionHistory: true
                              isAutoRejectEnabled: false
                              approvers:
                                userGroups:
                                  - shalinitest
                                minimumCount: 1
                                disallowPipelineExecutor: false
                              approverInputs: []
                        - step:
                            type: ShellScript
                            name: ShellScript_2
                            identifier: ShellScript_2
                            timeout: 10m
                            spec:
                              shell: Bash
                              onDelegate: true
                              source:
                                type: Inline
                                spec:
                                  script: |-
                                    exit 1
                                    echo "hi"
                              environmentVariables: []
                              outputVariables: []
        tags: {}
  variables: []
  notificationRules:
    - name: N1
      identifier: N1
      pipelineEvents:
        - type: StageFailed
          forStages:
            - PMS_Regression
            - Integration_CI_CD_CF
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: https://hooks.slack.com/services/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
      enabled: true
  allowStageExecutions: true
  identifier: NGPipelinesQAAPI_Shalinitest
  name: NG-Pipelines-QA-API - Shalini-test
