pipeline:
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags:
    ngPipelines: ""
    pipelineservice: ""
  stages:
    - stage:
        name: cs
        identifier: cs
        template:
          templateRef: parallelStepGroup
          versionLabel: v1
  variables: []
  notificationRules:
    - name: N1
      identifier: N1
      pipelineEvents:
        - type: StageFailed
          forStages:
            - PMS_Regression
            - Integration_CI_CD_CF
      notificationMethod:
        type: Slack
        spec:
          userGroups: []
          webhookUrl: https://hooks.slack.com/services/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
      enabled: true
  allowStageExecutions: true
  identifier: NGPipelinesQAAPI_Shalinitest
  name: NG-Pipelines-QA-API - Shalini-test
