pipeline:
  name: parent
  identifier: parent
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: chained
        identifier: chained
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childPipeline2
          project: naidusanity
          outputs:
            - name: timeout
              value: <+pipeline.stages.custome.spec.execution.steps.ShellScript_1.timeout>
          inputSetReferences:
            - <+pipeline.variables.input1>
            - input2
    - stage:
        name: stage2
        identifier: stage2
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childPipeline22
          project: naidusanity
          inputs:
            identifier: childPipeline22
            stages:
              - stage:
                  identifier: custom
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: ShellScript_1
                            type: ShellScript
                            timeout: <+stages.chained.output.timeout>
          outputs: []
        when:
          pipelineStatus: All
  variables:
    - name: input1
      type: String
      description: ""
      value: <+input>
    - name: input2
      type: String
      description: ""
      value: <+input>
