pipeline:
  name: setup reference pipeline default
  identifier: setup_reference_pipeline_default
  projectIdentifier: shalinitest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: stage_template_default
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: stage
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
