pipeline:
  name: test76
  identifier: test76
  projectIdentifier: shalinitest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ca
        identifier: ca
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: wait
                  identifier: wait
                  spec:
                    duration: 10m
        tags: {}
